CREATE PROCEDURE <schema>.proc_cols (parm1 VARCHAR(128), parm2 INTEGER)
	READS SQL DATA
	DYNAMIC RESULT SETS 1	
	LANGUAGE JAVA
	PARAMETER STYLE JAVA
	EXTERNAL NAME 'JavaPkgName.JavaClassName.javaSPName';